version: '3.8'
services:
  app:
    build:
      context: .
      args:
        ENVIRONMENT: prod
        DINAHOSTING_USER: ${DINAHOSTING_USER}
        DINAHOSTING_PASSWORD: ${DINAHOSTING_PASSWORD}
        DINAHOSTING_DOMAIN: ${DINAHOSTING_DOMAIN}
    ports:
      - "443:443"
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_USER: myusername
      DB_PASSWORD: mypassword
      DB_NAME: mydatabase
      DB_PORT: 5432
      ENV: "prod"
    volumes:
      - certbot_data:/etc/letsencrypt

  db:
    image: postgres:alpine
    environment:
      POSTGRES_USER: myusername
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydatabase
    volumes:
      - postgres_data:/var/lib/postgresql/data

  certbot:
    image: nbraun1/certbot
    environment:
      EMAIL: endikallano@gmail.com
      DOMAINS: opencurriculum.eus,www.opencurriculum.eus
      CRON: 0 3 1 * * # Run every first day of the month at 3:00
    ports:
      - "80:80"
    volumes:
      - certbot_data:/etc/letsencrypt

volumes:
  postgres_data:
  certbot_data:
