# Use the latest Golang base image
FROM golang:latest

# Set the current working directory inside the container
WORKDIR /app

# Copy go.mod and go.sum files to the workspace
COPY go.mod go.sum ./

# Download all dependencies
RUN go mod download

# Copy the source from the current directory to the workspace
COPY . .

# Build the Go app
RUN go build -o /tmp/main ./cmd/main.go

# Expose port 8080 to the outside world
EXPOSE 8080

# Install Air for development or run DNS script for production
RUN  curl -fLo install.sh https://raw.githubusercontent.com/cosmtrek/air/master/install.sh
RUN chmod +x install.sh && sh install.sh && mv ./bin/air /bin/

CMD ["air"]
