version: '3.8'
services:
  app:
    build:
      context: .
      args:
        ENVIRONMENT: prod
        DINAHOSTING_USER: ${DINAHOSTING_USER}
        DINAHOSTING_PASSWORD: ${DINAHOSTING_PASSWORD}
        DINAHOSTING_DOMAIN: ${DINAHOSTING_DOMAIN}
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_USER: myusername
      DB_PASSWORD: mypassword
      DB_NAME: mydatabase
      DB_PORT: 5432
      ENV: "prod"
    volumes:
      - cert_data:/certs

  db:
    image: postgres:alpine
    environment:
      POSTGRES_USER: myusername
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydatabase
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
  cert_data:
